{
  "cve_id": "CVE-2022-0523",
  "cwe_ids": [
    "CWE-416"
  ],
  "cvss_vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
  "cvss_is_v3": false,
  "repo_name": "radareorg/radare2",
  "commit_msg": "Fix UAF in pyc parser ##crash\n\n* Reported by Cen Zhang via huntr.dev\n* Reproducer: bins/fuzzed/harep2.pyc",
  "commit_hash": "35482cb760db10f87a62569e2f8872dbd95e9269",
  "git_url": "https://github.com/radareorg/radare2/commit/35482cb760db10f87a62569e2f8872dbd95e9269",
  "file_path": "libr/bin/format/pyc/marshal.c",
  "func_name": "get_list_object",
  "func_before": "static pyc_object *get_list_object(RBuffer *buffer) {\n\tpyc_object *ret = NULL;\n\tbool error = false;\n\tut32 n = 0;\n\n\tn = get_ut32 (buffer, &error);\n\tif (n > ST32_MAX) {\n\t\teprintf (\"bad marshal data (list size out of range)\\n\");\n\t\treturn NULL;\n\t}\n\tif (error) {\n\t\treturn NULL;\n\t}\n\tret = get_array_object_generic (buffer, n);\n\tif (ret) {\n\t\tret->type = TYPE_LIST;\n\t\treturn ret;\n\t}\n\treturn NULL;\n}",
  "abstract_func_before": "static pyc_object *get_list_object(RBuffer *VAR_0) {\n\tpyc_object *VAR_1 = NULL;\n\tbool VAR_2 = false;\n\tut32 VAR_3 = 0;\n\n\tVAR_3 = get_ut32 (VAR_0, &VAR_2);\n\tif (VAR_3 > VAR_4) {\n\t\teprintf (\"bad marshal data (list size out of range)\\n\");\n\t\treturn NULL;\n\t}\n\tif (VAR_2) {\n\t\treturn NULL;\n\t}\n\tVAR_1 = get_array_object_generic (VAR_0, VAR_3);\n\tif (VAR_1) {\n\t\tVAR_1->type = VAR_5;\n\t\treturn VAR_1;\n\t}\n\treturn NULL;\n}",
  "func_graph_path_before": "radareorg/radare2/35482cb760db10f87a62569e2f8872dbd95e9269/marshal.c/vul/before/2.json",
  "func": "static pyc_object *get_list_object(RBuffer *buffer) {\n\tpyc_object *ret = NULL;\n\tbool error = false;\n\tut32 n = get_ut32 (buffer, &error);\n\tif (n > ST32_MAX) {\n\t\teprintf (\"bad marshal data (list size out of range)\\n\");\n\t\treturn NULL;\n\t}\n\tif (error) {\n\t\treturn NULL;\n\t}\n\tret = get_array_object_generic (buffer, n);\n\tif (ret) {\n\t\tret->type = TYPE_LIST;\n\t\treturn ret;\n\t}\n\treturn NULL;\n}",
  "abstract_func": "static pyc_object *get_list_object(RBuffer *VAR_0) {\n\tpyc_object *VAR_1 = NULL;\n\tbool VAR_2 = false;\n\tut32 VAR_3 = get_ut32 (VAR_0, &VAR_2);\n\tif (VAR_3 > VAR_4) {\n\t\teprintf (\"bad marshal data (list size out of range)\\n\");\n\t\treturn NULL;\n\t}\n\tif (VAR_2) {\n\t\treturn NULL;\n\t}\n\tVAR_1 = get_array_object_generic (VAR_0, VAR_3);\n\tif (VAR_1) {\n\t\tVAR_1->type = VAR_5;\n\t\treturn VAR_1;\n\t}\n\treturn NULL;\n}",
  "func_graph_path": "radareorg/radare2/35482cb760db10f87a62569e2f8872dbd95e9269/marshal.c/vul/after/2.json",
  "diff_func": "--- func_before\n+++ func_after\n@@ -1,9 +1,7 @@\n static pyc_object *get_list_object(RBuffer *buffer) {\n \tpyc_object *ret = NULL;\n \tbool error = false;\n-\tut32 n = 0;\n-\n-\tn = get_ut32 (buffer, &error);\n+\tut32 n = get_ut32 (buffer, &error);\n \tif (n > ST32_MAX) {\n \t\teprintf (\"bad marshal data (list size out of range)\\n\");\n \t\treturn NULL;",
  "diff_line_info": {
    "deleted_lines": [
      "\tut32 n = 0;",
      "",
      "\tn = get_ut32 (buffer, &error);"
    ],
    "added_lines": [
      "\tut32 n = get_ut32 (buffer, &error);"
    ]
  },
  "is_vul": true,
  "pr_url": "https://github.com/radareorg/radare2/pull/19670",
  "description": "Failed to get PR details: HTTP Request Error for PR https://github.com/radareorg/radare2/pull/19670: 403 Client Error: Forbidden for url: https://api.github.com/repos/radareorg/radare2/pulls/19670",
  "Bug Filter": "Security Vulnerability Fix",
  "Bug Filter Confidence": 1.0,
  "Bug Filter Response": "**Final Classification:** Security Vulnerability Fix; **Confidence:** 1.0  \n\nThe commit message and code diff clearly indicate a fix for a Use-After-Free (UAF) vulnerability in the pyc parser, which is a security issue. The changes address memory management by properly handling buffer reads and checks, aligning with a security fix."
}